# Fluid Theme Configuration

# Navigation Bar
navbar:
  blog_title: WJY's Site
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill", name: "Home" }
    - { key: "projects", link: "/projects/", icon: "iconfont icon-code-fill", name: "Projects" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill", name: "Blog" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill", name: "About" }

# Language Switcher
fun_features:
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    loop: false
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: left
  copy_btn: true

# i18n
i18n:
  enable: true
  default: en
  available:
    - en
    - zh-CN

# Index Page
index:
  banner_img: /img/default.png
  banner_img_height: 100
  banner_mask_alpha: 0.3
  slogan:
    enable: true
    text: Welcome to My Blog
  auto_excerpt:
    enable: true

# 文章页
post:
  banner_img: /img/default.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
  meta:
    author:
      enable: true
    date:
      enable: true
      format: "YYYY-MM-DD"
    wordcount:
      enable: true
    min2read:
      enable: true
    views:
      enable: false

# 归档页
archive:
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3

# 分类页
category:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3

# 标签页
tag:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3

# About Page
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  avatar: /img/avatar.jpg
  name: Junyang Wang
  intro: PKU Student | Tech Enthusiast | Love Coding & Sharing
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/ID-WJY001", tip: "GitHub" }
    - { class: "iconfont icon-mail-fill", link: "mailto:junyangwang@stu.pku.edu.cn", tip: "Email" }

# 页脚
footer:
  content: |
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
  statistics:
    enable: false

# 网页统计
web_analytics:
  enable: false

# 暗色模式
dark_mode:
  enable: true
  default: auto
